//! Configuration loader for MaceLenia simulations.
//!
//! Loads simulation parameters from a JSON config file (generated by
//! `train/generate_kernel_json.py`) and FFT kernels from a binary file.
//! This is the single source of truth -- all parameters are dictated by
//! the Python generation script, not re-created in Rust.

use serde::Deserialize;

// ===========================================================================
// SimConfig -- mirrors the JSON structure from generate_kernel_json.py
// ===========================================================================

#[derive(Deserialize, Debug, Clone)]
pub struct SimConfig {
    pub seed_size: usize,
    pub num_channels: usize,
    pub num_kernels: usize,
    pub seed_channels: Vec<Vec<f64>>,
    pub c0: Vec<u32>,
    pub c1: Vec<u32>,
    pub growth_mu: Vec<f32>,
    pub growth_sigma: Vec<f32>,
    pub growth_weights: Vec<f32>,
    pub global_r: f64,
    pub radii: Vec<f64>,
    pub widths: Vec<f64>,
}

// ===========================================================================
// Loading
// ===========================================================================

/// Load a simulation config from a JSON file.
pub fn load_config(path: &str) -> SimConfig {
    let data = std::fs::read_to_string(path).expect("Failed to read config file");
    let config: SimConfig = serde_json::from_str(&data).expect("Failed to parse config JSON");
    println!("  Loaded config from {}", path);
    println!(
        "  {} channels, {} kernels, {}x{} grid",
        config.num_channels, config.num_kernels, config.seed_size, config.seed_size
    );
    config
}

/// Load FFT kernels from a binary file.
///
/// Format: for each kernel, `size x size` complex64 values stored as
/// `[re, im, re, im, ...]` in f32 little-endian.
///
/// If the stored kernel size differs from the target size, the kernels
/// are center-padded or used directly.
pub fn load_kernels(
    path: &str,
    num_kernels: usize,
    target_size: usize,
) -> Vec<Vec<num_complex::Complex32>> {
    let data = std::fs::read(path).expect("Failed to read kernel FFT file");
    let file_size = data.len();
    let kernel_bytes = file_size / num_kernels;
    let kernel_elems = kernel_bytes / 8;
    let src_size = (kernel_elems as f64).sqrt() as usize;

    let mut kernels = Vec::with_capacity(num_kernels);
    let kernel_len = target_size * target_size;

    for k in 0..num_kernels {
        let mut kernel = vec![num_complex::Complex32::new(0.0, 0.0); kernel_len];
        let base = k * kernel_bytes;

        if src_size == target_size {
            for i in 0..kernel_len {
                let offset = base + i * 8;
                let re = f32::from_le_bytes(data[offset..offset + 4].try_into().unwrap());
                let im = f32::from_le_bytes(data[offset + 4..offset + 8].try_into().unwrap());
                kernel[i] = num_complex::Complex32::new(re, im);
            }
        } else {
            let mut src = vec![num_complex::Complex32::new(0.0, 0.0); src_size * src_size];
            for i in 0..src_size * src_size {
                let offset = base + i * 8;
                let re = f32::from_le_bytes(data[offset..offset + 4].try_into().unwrap());
                let im = f32::from_le_bytes(data[offset + 4..offset + 8].try_into().unwrap());
                src[i] = num_complex::Complex32::new(re, im);
            }

            let half_src = src_size / 2;
            let mut centered = vec![num_complex::Complex32::new(0.0, 0.0); src_size * src_size];
            for i in 0..src_size {
                for j in 0..src_size {
                    let ni = (i + half_src) % src_size;
                    let nj = (j + half_src) % src_size;
                    centered[ni * src_size + nj] = src[i * src_size + j];
                }
            }

            let pad = (target_size - src_size) / 2;
            for i in 0..src_size {
                for j in 0..src_size {
                    kernel[(pad + i) * target_size + (pad + j)] = centered[i * src_size + j];
                }
            }

            let half_dst = target_size / 2;
            let mut result = vec![num_complex::Complex32::new(0.0, 0.0); kernel_len];
            for i in 0..target_size {
                for j in 0..target_size {
                    let ni = (i + half_dst) % target_size;
                    let nj = (j + half_dst) % target_size;
                    result[ni * target_size + nj] = kernel[i * target_size + j];
                }
            }
            kernel = result;
        }
        kernels.push(kernel);
    }
    println!(
        "  Loaded {} kernels from {} ({}x{} -> {}x{})",
        num_kernels, path, src_size, src_size, target_size, target_size
    );
    kernels
}
