// -*- coding: utf-8 -*-
// MaceLenia GPU simulation with video output.
// Requires --creature pointing to a creature name generated by generate_kernel_json.py.
// Loads seed/[creature].json and kernels/[creature]_[grid_size].bin.
#![allow(non_snake_case, dead_code)]

mod config;
mod orchestrator;
mod wfft;

use clap::Parser;
use config::{load_config, load_kernels};
use orchestrator::GpuMaceLenia;
use std::path::PathBuf;
use std::sync::Arc;
use wfft::WgpuContext;

// ---------------------------------------------------------------------------
// CLI arguments
// ---------------------------------------------------------------------------

#[derive(Parser)]
#[command(name = "ml-rs", about = "MaceLenia GPU simulation")]
struct Cli {
    /// Creature name. Loads config from seed/{creature}.json
    /// and kernels from kernels/{creature}_{grid_size}.bin.
    #[arg(long, required = true)]
    creature: String,

    /// Video duration in seconds
    #[arg(long, default_value_t = 60)]
    seconds: u32,

    /// Video frame rate
    #[arg(long, default_value_t = 60)]
    fps: u32,

    /// Output directory for video
    #[arg(long, default_value = "videos")]
    output: String,

    /// Simulation temperature (for diffusion affinity)
    #[arg(long, default_value_t = 1.0)]
    temp: f32,
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

fn setup_simulation(cli: &Cli) -> (Arc<WgpuContext>, GpuMaceLenia, usize) {
    let config_path = format!("seed/{}.json", cli.creature);

    // Load everything from config
    let cfg = load_config(&config_path);
    let grid_size = cfg.seed_size;
    let num_channels = cfg.num_channels;
    let num_kernels = cfg.num_kernels;

    println!(
        "  Using creature '{}': {}x{} grid, {} ch, {} kernels",
        cli.creature, grid_size, grid_size, num_channels, num_kernels
    );

    // wgpu setup (headless)
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        compatible_surface: None,
        force_fallback_adapter: false,
    }))
    .expect("No suitable GPU adapter found!");

    let (device, queue) = pollster::block_on(adapter.request_device(
        &wgpu::DeviceDescriptor {
            label: Some("MaceLenia Device"),
            features: wgpu::Features::empty(),
            limits: wgpu::Limits {
                max_buffer_size: 2 << 30,
                max_storage_buffer_binding_size: 2 << 30,
                ..Default::default()
            },
        },
        None,
    ))
    .expect("Failed to request GPU device!");

    let context = Arc::new(WgpuContext::from_device(device, queue));
    let shape = grid_size.next_power_of_two();

    let game = GpuMaceLenia::new(
        Arc::clone(&context),
        &[shape, shape],
        num_channels,
        num_kernels,
        &cfg.c0,
        &cfg.c1,
        &cfg.growth_mu,
        &cfg.growth_sigma,
        &cfg.growth_weights,
        cli.temp,
    );

    // Upload seed from config
    for (c, data) in cfg.seed_channels.iter().enumerate() {
        game.upload_channel(data, c);
    }

    // Upload kernels (with permutation to match Python state[:,:,None] indexing)
    let kernel_path = format!("kernels/{}_{}.bin", cli.creature, shape);
    let kernels_fft = load_kernels(&kernel_path, num_kernels, shape);
    for k in 0..num_kernels {
        let perm_idx = (k % num_channels) * num_channels + (k / num_channels);
        game.set_kernel(&kernels_fft[perm_idx], k);
    }

    println!("MaceLenia: GPU-Accelerated Multi-channel CA");
    println!(
        "{} channels, {} kernels, {}x{} grid",
        num_channels, num_kernels, grid_size, grid_size,
    );

    (context, game, grid_size)
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fn main() {
    let cli = Cli::parse();
    run_video(cli);
}

// ---------------------------------------------------------------------------
// Video mode: headless frame generation + ffmpeg encoding
// ---------------------------------------------------------------------------

fn run_video(cli: Cli) {
    let (_context, game, grid_size) = setup_simulation(&cli);

    let total_frames = (cli.seconds as u64) * (cli.fps as u64);
    let output_path = format!("{}/ml_output.mp4", cli.output);
    let output_dir = PathBuf::from(&cli.output);

    std::fs::create_dir_all(&output_dir).expect("Failed to create output directory");

    println!(
        "Generating {} frames at {} FPS ({} seconds)",
        total_frames, cli.fps, cli.seconds
    );
    println!("Output: {}", output_path);

    let shape = grid_size;

    // Spawn ffmpeg and pipe raw RGB frames to its stdin
    let mut ffmpeg = std::process::Command::new("ffmpeg")
        .args(&[
            "-y",
            "-f",
            "rawvideo",
            "-pixel_format",
            "rgb24",
            "-video_size",
            &format!("{}x{}", shape, shape),
            "-framerate",
            &cli.fps.to_string(),
            "-i",
            "-",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
            &output_path,
        ])
        .stdin(std::process::Stdio::piped())
        .spawn()
        .expect("Failed to spawn ffmpeg. Is ffmpeg installed?");

    let mut stdin = ffmpeg.stdin.take().expect("Failed to open ffmpeg stdin");

    for step in 0..total_frames {
        game.iterate();

        if step % cli.fps as u64 == 0 {
            let elapsed_secs = step / cli.fps as u64;
            print!(
                "\rFrame {}/{} ({}s)...",
                step + 1,
                total_frames,
                elapsed_secs
            );
            use std::io::Write;
            std::io::stdout().flush().unwrap();
        }

        let data = game.download_all_channels();

        // Map channels to RGB:
        //   c0 -> R, c1 -> G, c2 -> B
        //   color = clamp(channel * 1.5, 0, 1), then gamma = sqrt(color)
        let mut pixels = vec![0u8; shape * shape * 3];
        for i in 0..shape {
            for j in 0..shape {
                let idx = i * shape + j;
                let c0 = data[0 * shape * shape + idx];
                let c1 = data[1 * shape * shape + idx];
                let c2 = data[2 * shape * shape + idx];
                let r = (c0 * 1.5).clamp(0.0, 1.0).sqrt();
                let g = (c1 * 1.5).clamp(0.0, 1.0).sqrt();
                let b = (c2 * 1.5).clamp(0.0, 1.0).sqrt();
                let p = idx * 3;
                pixels[p] = (r * 255.0) as u8;
                pixels[p + 1] = (g * 255.0) as u8;
                pixels[p + 2] = (b * 255.0) as u8;
            }
        }

        // Write raw RGB frame to ffmpeg stdin
        use std::io::Write;
        stdin
            .write_all(&pixels)
            .expect("Failed to write frame to ffmpeg");
    }

    println!("\nClosing ffmpeg...");
    drop(stdin);
    let status = ffmpeg.wait().expect("Failed to wait for ffmpeg");

    if status.success() {
        println!("Video saved to: {}", output_path);
    } else {
        eprintln!("ffmpeg encoding failed (exit code: {:?})", status.code());
    }
}
