// -*- coding: utf-8 -*-
// Profile each phase of the MaceLenia GPU pipeline.
// Requires --creature pointing to a creature name generated by generate_kernel_json.py.
#![allow(non_snake_case, dead_code)]

mod config;
mod orchestrator;
mod wfft;

use config::{load_config, load_kernels};
use orchestrator::GpuMaceLenia;
use std::sync::Arc;
use std::time::Instant;
use wfft::WgpuContext;

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fn main() {
    let args: Vec<String> = std::env::args().collect();

    // Find --creature (required)
    let creature_pos = args
        .iter()
        .position(|a| a == "--creature")
        .expect("--creature is required");
    let creature = args
        .get(creature_pos + 1)
        .expect("--creature requires a name argument");

    let config_path = format!("seed/{}.json", creature);
    let cfg = load_config(&config_path);
    let shape = cfg.seed_size.next_power_of_two();
    let num_channels = cfg.num_channels;
    let num_kernels = cfg.num_kernels;
    let num_warmup: usize = 20;
    let num_profile: usize = 100;

    // --- wgpu setup (headless) ---
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        compatible_surface: None,
        force_fallback_adapter: false,
    }))
    .expect("No suitable GPU adapter found!");

    let (device, queue) = pollster::block_on(adapter.request_device(
        &wgpu::DeviceDescriptor {
            label: Some("MaceLenia Device"),
            features: wgpu::Features::empty(),
            limits: wgpu::Limits {
                max_buffer_size: 2 << 30,
                max_storage_buffer_binding_size: 2 << 30,
                ..Default::default()
            },
        },
        None,
    ))
    .expect("Failed to request GPU device!");

    let context = Arc::new(WgpuContext::from_device(device, queue));

    // --- MaceLenia setup ---
    let game = GpuMaceLenia::new(
        Arc::clone(&context),
        &[shape, shape],
        num_channels,
        num_kernels,
        &cfg.c0,
        &cfg.c1,
        &cfg.growth_mu,
        &cfg.growth_sigma,
        &cfg.growth_weights,
        0.2,
        1.0,
    );

    // Upload seed from config
    for (c, data) in cfg.seed_channels.iter().enumerate() {
        game.upload_channel(data, c);
    }

    // Upload kernels (with permutation to match Python state[:,:,None] indexing)
    let kernel_path = format!("kernels/{}_{}.bin", creature, shape);
    let kernels_fft = load_kernels(&kernel_path, num_kernels, shape);
    for k in 0..num_kernels {
        let perm_idx = (k % num_channels) * num_channels + (k / num_channels);
        game.set_kernel(&kernels_fft[perm_idx], k);
    }

    println!("\n=== Profiling {}x{} grid ===", shape, shape);
    println!("Warming up {} iterations...", num_warmup);
    for _ in 0..num_warmup {
        game.iterate();
    }
    context.device.poll(wgpu::Maintain::Wait);

    // --- Profile full iteration ---
    println!("Profiling {} iterations...", num_profile);
    let start = Instant::now();
    for _ in 0..num_profile {
        game.iterate();
    }
    context.device.poll(wgpu::Maintain::Wait);
    let total_elapsed = start.elapsed();
    let avg_ms = total_elapsed.as_secs_f64() * 1000.0 / num_profile as f64;
    let fps = num_profile as f64 / total_elapsed.as_secs_f64();
    println!("\n  Full iteration: {:8.3} ms avg ({:.1} FPS)", avg_ms, fps);

    // --- Profile per-phase breakdown ---
    println!(
        "\n  Per-phase breakdown ({} warmup + {} measured):",
        num_warmup, num_profile
    );
    println!("  {:30} {:>10} {:>10}", "Phase", "ms", "% of total");
    println!("  {:-<30} {:->10} {:->10}", "", "", "");

    // Warmup
    for _ in 0..num_warmup {
        game.timed_iterate();
    }

    // Profile
    let mut phase_totals = [0.0f64; 4];
    for _ in 0..num_profile {
        let times = game.timed_iterate();
        for i in 0..4 {
            phase_totals[i] += times[i];
        }
    }

    let phase_names = [
        "Convolution (FFT+cmul+IFFT)",
        "Growth + weighted sum",
        "Diffusion (aff_exp + Z + redistribute)",
        "Buffer copy",
    ];
    let total_phase: f64 = phase_totals.iter().sum();
    for i in 0..4 {
        let avg = phase_totals[i] / num_profile as f64;
        let pct = avg / (total_phase / num_profile as f64) * 100.0;
        println!("  {:30} {:8.3} ms  {:6.1}%", phase_names[i], avg, pct);
    }
    println!("  {:-<30} {:->10} {:->10}", "", "", "");
    println!(
        "  {:30} {:8.3} ms  {:6.1}%",
        "Sum (serialized)",
        total_phase / num_profile as f64,
        100.0
    );
    println!();
    println!("  Note: serialized timing adds submit+sync overhead.");
    println!("  Actual parallel time: {:.3} ms ({:.1} FPS)", avg_ms, fps);
}
