// -*- coding: utf-8 -*-
// Generate PNG frames using the ml-rs GPU implementation.
// Requires --creature pointing to a creature name generated by generate_kernel_json.py.
#![allow(non_snake_case, dead_code)]

mod config;
mod orchestrator;
mod wfft;

use config::{load_config, load_kernels};
use orchestrator::GpuMaceLenia;
use std::sync::Arc;
use wfft::WgpuContext;

// ---------------------------------------------------------------------------
// PNG saving
// ---------------------------------------------------------------------------

fn save_png(data: &[f32], size: usize, path: &str) {
    let num_channels = data.len() / (size * size);
    let mut min_val = f32::INFINITY;
    let mut max_val = f32::NEG_INFINITY;
    let mut pixels = vec![0u8; size * size];
    for i in 0..size {
        for j in 0..size {
            let mut sum = 0.0f32;
            for c in 0..num_channels {
                sum += data[c * size * size + i * size + j];
            }
            if sum < min_val {
                min_val = sum;
            }
            if sum > max_val {
                max_val = sum;
            }
        }
    }
    let range = max_val - min_val;
    for i in 0..size {
        for j in 0..size {
            let mut sum = 0.0f32;
            for c in 0..num_channels {
                sum += data[c * size * size + i * size + j];
            }
            let normalized = if range > 0.0 {
                (sum - min_val) / range
            } else {
                0.0
            };
            pixels[i * size + j] = (normalized * 255.0) as u8;
        }
    }
    image::save_buffer(
        path,
        &pixels,
        size as u32,
        size as u32,
        image::ColorType::L8,
    )
    .unwrap();
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

fn main() {
    let args: Vec<String> = std::env::args().collect();

    // Find --creature (required)
    let creature_pos = args
        .iter()
        .position(|a| a == "--creature")
        .expect("--creature is required");
    let creature = args
        .get(creature_pos + 1)
        .expect("--creature requires a name argument");

    let config_path = format!("seed/{}.json", creature);
    let cfg = load_config(&config_path);
    let shape = cfg.seed_size.next_power_of_two();
    let num_channels = cfg.num_channels;
    let num_kernels = cfg.num_kernels;
    let num_steps: usize = 50;

    // --- wgpu setup (headless, no window) ---
    let instance = wgpu::Instance::default();
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        compatible_surface: None,
        force_fallback_adapter: false,
    }))
    .expect("No suitable GPU adapter found!");

    let (device, queue) = pollster::block_on(adapter.request_device(
        &wgpu::DeviceDescriptor {
            label: Some("MaceLenia Device"),
            features: wgpu::Features::empty(),
            limits: wgpu::Limits {
                max_buffer_size: 2 << 30,
                max_storage_buffer_binding_size: 2 << 30,
                ..Default::default()
            },
        },
        None,
    ))
    .expect("Failed to request GPU device!");

    let context = Arc::new(WgpuContext::from_device(device, queue));

    // --- MaceLenia setup ---
    let game = GpuMaceLenia::new(
        Arc::clone(&context),
        &[shape, shape],
        num_channels,
        num_kernels,
        &cfg.c0,
        &cfg.c1,
        &cfg.growth_mu,
        &cfg.growth_sigma,
        &cfg.growth_weights,
        1.0,
    );

    // Upload seed from config
    for (c, data) in cfg.seed_channels.iter().enumerate() {
        game.upload_channel(data, c);
    }

    // Upload kernels (with permutation to match Python state[:,:,None] indexing)
    let kernel_path = format!("kernels/{}_{}.bin", creature, shape);
    let kernels_fft = load_kernels(&kernel_path, num_kernels, shape);
    for k in 0..num_kernels {
        let perm_idx = (k % num_channels) * num_channels + (k / num_channels);
        game.set_kernel(&kernels_fft[perm_idx], k);
    }

    // Save initial state
    std::fs::create_dir_all("pngs").unwrap();
    let initial_data = game.download_all_channels();
    save_png(
        &initial_data,
        shape,
        &format!("pngs/ml_rs_frame_{:04}.png", 0),
    );
    println!("Saved frame 0");

    // Run steps and save PNGs
    for step in 1..=num_steps {
        game.run_steps(1);
        let data = game.download_all_channels();
        let path = format!("pngs/ml_rs_frame_{:04}.png", step);
        save_png(&data, shape, &path);
        println!("Saved frame {}", step);
    }

    println!("\nDone! Saved {} frames to pngs/", num_steps + 1);
}
