#!/usr/bin/env python3
"""Generate PNG frames matching ml-rs GPU implementation exactly.
Loads all parameters from a JSON config file (generated by generate_kernel_json.py)."""
import sys
import os
import argparse
import json
import struct
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import torch
from diff_lenia_org import DiffusionLenia
from PIL import Image

os.makedirs("pngs", exist_ok=True)

parser = argparse.ArgumentParser(description="Generate MaceLenia PNG frames (matching ml-rs)")
parser.add_argument("--creature", type=str, default=None,
                    help="Creature name. Loads seed/{name}.json and kernels/{name}_{grid_size}.bin")
parser.add_argument("--grid-size", type=int, default=64, choices=[64, 128, 256, 512],
                    help="Grid size (default: 64, only used without --creature)")
args = parser.parse_args()

# ---------------------------------------------------------------------------
# Load config or use procedural defaults
# ---------------------------------------------------------------------------
if args.creature is not None:
    config_path = f"seed/{args.creature}.json"
    with open(config_path) as f:
        cfg = json.load(f)
    GRID = cfg["seed_size"]
    C = cfg["num_channels"]
    K = cfg["num_kernels"]
    DT = 0.2
    NUM_STEPS = 50

    # Load seed channels from config
    seed_channels = np.array(cfg["seed_channels"], dtype=np.float64)  # (C, H*W)
    state_init = torch.from_numpy(seed_channels.reshape(1, C, GRID, GRID)).float()

    # Build params dict from config values
    mu = np.zeros((1, C, C), dtype=np.float32)
    sigma = np.zeros((1, C, C), dtype=np.float32)
    weights = np.zeros((1, C, C), dtype=np.float32)
    for k in range(K):
        out_ch = cfg["c1"][k]
        in_ch = cfg["c0"][k]
        mu[0, out_ch, in_ch] = cfg["growth_mu"][k]
        sigma[0, out_ch, in_ch] = cfg["growth_sigma"][k]
        weights[0, out_ch, in_ch] = cfg["growth_weights"][k]

    # Dummy ring params (needed for init, will be overridden by FFT kernels)
    rings = 3
    k_size = 25
    beta = np.zeros((1, C, C, rings), dtype=np.float32)
    mu_k = np.zeros((1, C, C, rings), dtype=np.float32)
    sigma_k = np.ones((1, C, C, rings), dtype=np.float32)

    params = {
        'k_size': k_size,
        'mu': torch.from_numpy(mu).float(),
        'sigma': torch.from_numpy(sigma).float(),
        'beta': torch.from_numpy(beta).float(),
        'mu_k': torch.from_numpy(mu_k).float(),
        'sigma_k': torch.from_numpy(sigma_k).float(),
        'weights': torch.from_numpy(weights).float(),
    }

    # Load FFT kernels from binary file
    kernel_path = f"kernels/{args.creature}_{GRID}.bin"
    with open(kernel_path, "rb") as f:
        raw = f.read()
    kernel_size = GRID
    kernel_bytes = len(raw) // K
    kernels_fft_np = np.zeros((K, kernel_size, kernel_size), dtype=np.complex64)
    for k in range(K):
        base = k * kernel_bytes
        for i in range(kernel_size * kernel_size):
            offset = base + i * 8
            re = struct.unpack_from("f", raw, offset)[0]
            im = struct.unpack_from("f", raw, offset + 4)[0]
            kernels_fft_np[k, i // kernel_size, i % kernel_size] = complex(re, im)

    # Reshape to (B, C, C, H, W) -- kernel[out, in] = kernel for in->out
    kernels_fft_torch = torch.zeros((1, C, C, GRID, GRID), dtype=torch.complex64)
    for k in range(K):
        out_ch = cfg["c1"][k]
        in_ch = cfg["c0"][k]
        kernels_fft_torch[0, out_ch, in_ch] = torch.from_numpy(kernels_fft_np[k])

else:
    # Procedural fallback (original behavior)
    GRID = args.grid_size
    C = 3
    K = C * C
    DT = 0.2
    NUM_STEPS = 50

    def sigmoid(x):
        return 0.5 * (np.tanh(x / 2.0) + 1.0)

    def generate_kernels_fft(size, num_kernels):
        mid = size // 2
        global_r = 10.0
        kernels_spatial = np.zeros((num_kernels, size, size), dtype=np.float32)
        for k in range(num_kernels):
            radius = 0.5 + 0.3 * (k / num_kernels)
            width = 0.05 + 0.03 * (k / num_kernels)
            for i in range(size):
                for j in range(size):
                    di = i - mid
                    dj = j - mid
                    dist = np.sqrt(float(di * di + dj * dj))
                    d_scaled = dist / (global_r * radius)
                    sig = sigmoid(-(d_scaled - 1.0) * 10.0)
                    diff = d_scaled - 0.5
                    ker_val = np.exp(-(diff * diff) / (2.0 * width * width))
                    kernels_spatial[k, i, j] = sig * ker_val
            total = kernels_spatial[k].sum()
            if total > 0:
                kernels_spatial[k] /= total
            shifted = np.zeros_like(kernels_spatial[k])
            half = size // 2
            for i in range(size):
                for j in range(size):
                    ni = (i + half) % size
                    nj = (j + half) % size
                    shifted[ni, nj] = kernels_spatial[k, i, j]
            kernels_spatial[k] = shifted
        kernels_fft = np.fft.fft2(kernels_spatial, axes=(-2, -1))
        return kernels_fft

    mu = np.zeros((1, C, C), dtype=np.float32)
    sigma = np.zeros((1, C, C), dtype=np.float32)
    weights = np.zeros((1, C, C), dtype=np.float32)
    for k in range(K):
        out_ch = k // C
        in_ch = k % C
        mu[0, out_ch, in_ch] = 0.1 + 0.05 * (k / K)
        sigma[0, out_ch, in_ch] = 0.05 + 0.03 * (k / K)
        weights[0, out_ch, in_ch] = 1.0 / C

    rings = 3
    k_size = 25
    beta = np.zeros((1, C, C, rings), dtype=np.float32)
    mu_k = np.zeros((1, C, C, rings), dtype=np.float32)
    sigma_k = np.ones((1, C, C, rings), dtype=np.float32)

    params = {
        'k_size': k_size,
        'mu': torch.from_numpy(mu).float(),
        'sigma': torch.from_numpy(sigma).float(),
        'beta': torch.from_numpy(beta).float(),
        'mu_k': torch.from_numpy(mu_k).float(),
        'sigma_k': torch.from_numpy(sigma_k).float(),
        'weights': torch.from_numpy(weights).float(),
    }

    # Gaussian blob seed
    A = np.zeros((1, C, GRID, GRID), dtype=np.float64)
    cx, cy = GRID / 2.0, GRID / 2.0
    variance = (GRID * GRID) / 64.0
    for i in range(GRID):
        for j in range(GRID):
            dx, dy = i - cx, j - cy
            dist = np.sqrt(dx * dx + dy * dy)
            val = np.exp(-dist * dist / variance)
            for c in range(C):
                A[0, c, i, j] = val * (0.5 + 0.5 * c / C)
    state_init = torch.from_numpy(A).float()

    # Procedural FFT kernels
    kernels_fft_np = generate_kernels_fft(GRID, K)
    kernels_fft_torch = torch.zeros((1, C, C, GRID, GRID), dtype=torch.complex64)
    for k in range(K):
        out_ch = k // C
        in_ch = k % C
        kernels_fft_torch[0, out_ch, in_ch] = torch.from_numpy(kernels_fft_np[k])

# ---------------------------------------------------------------------------
# Create DiffusionLenia automaton
# ---------------------------------------------------------------------------
device = 'cuda' if torch.cuda.is_available() else 'mps' if torch.backends.mps.is_available() else 'cpu'
print(f"Using device: {device}")

lenia = DiffusionLenia(
    size=(1, GRID, GRID),
    dt=DT,
    num_channels=C,
    params=params,
    state_init=state_init,
    device=device,
)

# Override FFT kernels
lenia.fft_kernel = kernels_fft_torch.to(device)

# ---------------------------------------------------------------------------
# Save frames
# ---------------------------------------------------------------------------
def save_frame(arr, step):
    """Save a frame as PNG. arr shape (C, H, W)."""
    img = np.sum(arr, axis=0)  # (H, W)
    lo, hi = img.min(), img.max()
    if hi > lo:
        img = (img - lo) / (hi - lo) * 255
    else:
        img = np.zeros_like(img)
    img = img.astype(np.uint8)
    Image.fromarray(img).convert('L').save(f'pngs/py_frame_{step:04d}.png')

# Save initial state
initial_state = lenia.state.detach().cpu().numpy()[0]
save_frame(initial_state, 0)

# Run steps and save frames
for step in range(1, NUM_STEPS + 1):
    lenia.step()
    state = lenia.state.detach().cpu().numpy()[0]
    save_frame(state, step)

print(f"Saved {NUM_STEPS + 1} Python frames (step 0 + {NUM_STEPS} steps) to pngs/ ({GRID}x{GRID})")
print("  py_frame_0000.png through py_frame_{:04d}.png".format(NUM_STEPS))
